# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jaxDiversity',
                'doc_host': 'https://Anil Radhakrishnan.github.io',
                'git_url': 'https://github.com/Anil Radhakrishnan/jaxDiversity',
                'lib_path': 'jaxDiversity'},
  'syms': {'jaxDiversity.core': {'jaxDiversity.core.foo': ('core.html#foo', 'jaxDiversity/core.py')}}}
