name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    strategy:
      fail-fast: true
      matrix:
        version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        with:
          version: ${{ matrix.version }}
